name: Deploy site 

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run deploy script
      run: |
        chmod +x ./deploy.sh
        ./deploy.sh